import Chat from "/components/chat/Chat";
import styles from "/css/messages.module.css";
import ChatMessages from "/components/chat/ChatMessages";


export default function ChatPage() {


    return (
        <>
        <div className={styles.chats}>
            <div className={styles.conversationsContainer}>
                <h2>Chats</h2>
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
                <Chat
                    user="Joel"
                    time={"20:00"}
                    lastMessage={"fsdkfjaskfj"}
                    authorMessage={"Aaron"}
                    image={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyI9Cvp53aaP9XeRn-ZKbJDH2QaWC72O26A&s"}
                />
                <Chat
                    user="Oscar"
                    time={"20:00"}
                    authorMessage={"Aaron"}
                    lastMessage={"fsdkfjaskfj"}
                    image={"https://s2.abcstatics.com/media/bienestar/2022/06/01/jesus-matos-2-kQVC--1248x698@abc.png"}
                />
            </div>
            <ChatMessages />
        </div>
        </>
    )
}

