import { Inter, Montserrat } from "next/font/google";
import "/css/globals.css";
import Providers from "./providers";
import NavbarApp from "../../components/navigation/navbar";
const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({
  weight: ['100', '200', '500', '600', '800', '900'],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-montserrat"
})

export const metadata = {
  title: "Electricidad Total",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-main-color text-white">
      <body className={montserrat.className + "" }>
        <Providers>

             <NavbarApp/>
     
          <div className="">
             {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
