import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import NavbarApp from "../../components/navigation/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Electricidad Total",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-main-color text-white">
      <body className={inter.className + "" }>
        <Providers>

             <NavbarApp/>
     
          <div className="">
             {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
